# .github/workflows/create-linear-draft.yml
name: Create or Comment Linear Issue on Push

on:
  push:
    branches: [main]

jobs:
  handle-linear:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install deps
        run: npm install tsx @linear/sdk

      - name: Run Linear Draft Handler
        env:
          LINEAR_ACCESS_TOKEN: ${{ secrets.LINEAR_ACCESS_TOKEN }}
        run: npx tsx .github/scripts/createLinearDraft.ts
